#!/usr/bin/env bash

# $1 is the name of the example.

source $ZEPHYR/zephyr-env.sh
rm -rf $ROOT/build/zephyr-$1
cmake -B $ROOT/build/zephyr-$1 -DBOARD=m2sf_algol $ZEPHYR/samples/$1
make -C $ROOT/build/zephyr-$1
